from cvxpy.atoms import *
from cvxpy.reductions.dcp2cone.atom_canonicalizers.abs import *

canon_methods = {
		# affine_prod : affine_prod_canon,
		# geo_mean : geo_mean_canon,
		# harmonic_mean : harmonic_mean_canon,
		# lambda_max : lambda_max_canon,
		# lambda_min : lambda_min_canon,
		# lambda_sum_largest : lambda_sum_largest_canon,
		# lambda_sum_smallest : lambda_sum_smallest_canon,
		# log_det : log_det_canon,
		# log_sum_exp : log_sum_exp_canon,
		# matrix_frac : matrix_frac_canon,
		# max_entries : max_entries_canon,
		# min_entries : min_entries_canon,
		# norm : norm_canon,
		# norm1 : norm1_canon,
		# norm2 : norm2_canon,
		# norm_inf : normInf_canon,
		# norm_nuc : normNuc_canon,
		# mixed_norm : mixed_norm_canon,
		# pnorm : pnorm_canon,
		# quad_form : quad_form_canon,
		# quad_over_lin : quad_over_lin_canon,
		# sigma_max : sigma_max_canon,
		# sum_largest : sum_largest_canon,
		# sum_smallest : sum_smallest_canon,
		# sum_squares : sum_squares_canon,
		# total_variation : tv_canon,
		abs : abs_canon,
		# entr : entr_canon,
		# exp : exp_canon,
		# huber : huber_canon,
		# inv_pos : inv_pos_canon,
		# kl_div : kl_div_canon,
		# log : log_canon,
		# log1p : log1p_canon,
		# logistic : logistic_canon,
		# max_elemwise : max_elemwise_canon,
		# min_elemwise : min_elemwise_canon,
		# neg : neg_canon,
		# pos : pos_canon,
		# power : power_canon,
		# scalene : scalene_canon,
		# sqrt : sqrt_canon,
		# square : square_canon,
}

