language: python
python:
  - "2.7"
  - "3.4"
os:
  - linux

before_install:
  # conda-based environment instead
  - deactivate

  # use miniconda installer
  - wget http://repo.continuum.io/miniconda/Miniconda-3.9.1-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh && ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

  # install deps
  - deps="nomkl pip numpy scipy"
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH

  # cvxpy dependency
  - sudo apt-get install -qq libatlas-base-dev gfortran
  - export ATLAS="/usr/lib/atlas-base/libatlas.so"

# command to install dependencies
install:
  # compiling library
  - python setup.py install

  # adding cvxpy
  - cd tests
  - git clone https://github.com/cvxgrp/cvxpy.git
  - cd cvxpy
  - python setup.py install
  - pip install nose

# command to run tests
script:  nosetests cvxpy

notifications:
  email: false
