python:
  - 2.7
  - 3.5
  - 3.6
numpy:
  - 1.11
c_compiler:
  - vs2008                     # [win]
  - vs2015                     # [win]
  - vs2015                     # [win]
cxx_compiler:
  - vs2008                     # [win]
  - vs2015                     # [win]
  - vs2015                     # [win]
zip_keys:
  -                             # [win]
    - c_compiler                # [win]
    - cxx_compiler              # [win]
    - python                    # [win]
