package:
  name: cvxpy
  version: "1.0.24"

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - setuptools
    - six
    - python
    - osqp
    - ecos >=2
    - scs >=1.1.3
    - multiprocess
    - numpy >=1.14
    - scipy >=0.15
    - libgcc # [not win]
    - lapack
    - mkl

  run:
    - python
    - osqp
    - ecos >=2
    - scs >=1.1.3
    - multiprocess
    - six
    - numpy >=1.9
    - scipy >=0.15
    - libgcc # [not win]
    - lapack
    - mkl

test:
  # Python imports
  imports:
    - cvxpy
    - cvxpy.atoms
    - cvxpy.atoms.affine
    - cvxpy.atoms.elementwise
    - cvxpy.cvxcore
    - cvxpy.cvxcore.python
    - cvxpy.constraints
    - cvxpy.expressions
    - cvxpy.expressions.constants
    - cvxpy.interface
    - cvxpy.interface.numpy_interface
    - cvxpy.lin_ops
    - cvxpy.problems
    - cvxpy.reductions
    - cvxpy.reductions.complex2real
    - cvxpy.reductions.complex2real.atom_canonicalizers
    - cvxpy.reductions.dcp2cone
    - cvxpy.reductions.dcp2cone.atom_canonicalizers
    - cvxpy.reductions.eliminate_pwl
    - cvxpy.reductions.eliminate_pwl.atom_canonicalizers
    - cvxpy.reductions.qp2quad_form
    - cvxpy.reductions.qp2quad_form.atom_canonicalizers
    - cvxpy.reductions.eliminate_pwl.atom_canonicalizers
    - cvxpy.reductions.solvers
    - cvxpy.reductions.solvers.conic_solvers
    - cvxpy.reductions.solvers.qp_solvers
    - cvxpy.reductions.solvers.lp_solvers
    - cvxpy.tests
    - cvxpy.transforms
    - cvxpy.utilities
    - cvxpy.cvxcore.python

about:
  home: http://github.com/cvxgrp/cvxpy/
  license: Apache License, Version 2.0
  summary: 'A domain-specific language for modeling convex optimization problems in Python.'
