# conda build conda-recipe -c omnia -c groakat -c mlgill
# conda install -c omnia -c stevend2 -c groakat -c mlgill cvxpy
package:
  name: cvxpy
  version: 0.4.11

build:
  number: 0

source:
  git_url: https://github.com/cvxgrp/cvxpy

requirements:
  build:
    - python
    - numpy
    - scipy
    - multiprocess
    - toolz
    - scs
    - ecos
    - cvxopt
    - setuptools
    - cvxcanon
  run:
    - python
    - numpy
    - scipy
    - multiprocess
    - toolz
    - scs
    - ecos
    - cvxopt
    - cvxcanon
test:
  requires:
    - setuptools
  imports:
    - cvxpy
about:
  home: http://www.cvxpy.org/en/latest/
  license: https://github.com/cvxgrp/cvxpy
  summary: A Python-embedded modeling language for convex optimization.