package:
  name: cvxpy
  version: "1.1.17"

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.15
    - scipy >=1.1
    - libgcc # [not win]

  run:
    - python
    - osqp >=0.4.1
    - ecos >=2
    - scs >=1.1
    - numpy >=1.15
    - scipy >=1.1
    - lapack
    - mkl

test:
  requires:
    - pytest

  # Python imports
  imports:
    - cvxpy
    - cvxpy.atoms
    - cvxpy.atoms.affine
    - cvxpy.atoms.elementwise
    - cvxpy.cvxcore
    - cvxpy.cvxcore.python
    - cvxpy.constraints
    - cvxpy.expressions
    - cvxpy.expressions.constants
    - cvxpy.interface
    - cvxpy.interface.numpy_interface
    - cvxpy.lin_ops
    - cvxpy.problems
    - cvxpy.reductions
    - cvxpy.reductions.complex2real
    - cvxpy.reductions.complex2real.atom_canonicalizers
    - cvxpy.reductions.dcp2cone
    - cvxpy.reductions.dcp2cone.atom_canonicalizers
    - cvxpy.reductions.eliminate_pwl
    - cvxpy.reductions.eliminate_pwl.atom_canonicalizers
    - cvxpy.reductions.qp2quad_form
    - cvxpy.reductions.qp2quad_form.atom_canonicalizers
    - cvxpy.reductions.eliminate_pwl.atom_canonicalizers
    - cvxpy.reductions.solvers
    - cvxpy.reductions.solvers.conic_solvers
    - cvxpy.reductions.solvers.qp_solvers
    - cvxpy.reductions.solvers.lp_solvers
    - cvxpy.tests
    - cvxpy.transforms
    - cvxpy.utilities
    - cvxpy.cvxcore.python

  commands:
    - pytest cvxpy/tests
    - pytest cvxpy/performance_tests

about:
  home: http://github.com/cvxpy/cvxpy/
  license: Apache License, Version 2.0
  summary: 'A domain-specific language for modeling convex optimization problems in Python.'
