from abs import abs
from geo_mean import geo_mean
from max import max
from min import min
from norm1 import norm1
from norm2 import norm2
from norm_inf import normInf
from quad_over_lin import quad_over_lin
from sqrt import sqrt
from square import square
from vstack import vstack