name: benchmark

on:
  pull_request:
    branches: [ master ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

  # build
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
        cache: 'pip' # cache for faster build
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    - name: Install package
      run: |
        pip install -e .
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  # benchmark:
    - name: Install benchmark package
      run: |
        pip install -r requirements_benchmark.txt
    - name: Benchmark test
      run: |
        python cvxpy/benchmarks/run_benchmarks.py

  # commit:
    - name: Commit files
      run: |
        git config --local user.name "benchmarkjob"
        git add -f cvxpy/benchmarks/benchmark_report.md
        git commit -m "Updating benchmark result"
    - name: Push changes 
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
        force: true
