name: deploy-book

on: [push]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:    
  deploy-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/checkout@v2
      - name: Install cvxpy dependencies and jupyter-book, install the kernel
        run: |
          pip install .
          pip install jupyter-book
          ipython kernel install --name "cvxpy" --user
        
      # Build the book
      - name: Build the book
        run: |
          jupyter-book clean book
          jupyter-book build book
          cp -r book/_build/html ./docs

      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book/_build/html

