name: test_cvxpygen

on:
    pull_request:
    push:
        branches:
            - master
        tags:
          - '*'
jobs:
  test_cvxpygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.11"
          enable-cache: true
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install libeigen3-dev
      - name: Install CVXPY
        run: |
          uv venv --seed
          uv pip install .
      - name: Install CVXPYlayers
        run: |
          git clone https://github.com/cvxpy/cvxpylayers.git
          cd cvxpylayers
          git checkout custom-solvers  # TEMPORARY until that PR is merged
          uv pip install ".[torch, jax]"
      - name: Install CVXPYgen
        run: |
          git clone --recurse-submodules https://github.com/cvxgrp/cvxpygen.git
          cd cvxpygen
          uv pip install .[dev]
      - name: Run CVXPYgen tests
        run: |
          uv run --no-sync pytest cvxpygen/tests
