name: test_cvxpygen

on:
    pull_request:
    push:
        branches:
            - master
        tags:
          - '*'
jobs:
  test_cvxpygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.11"
          enable-cache: true
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install libeigen3-dev
      - name: Install cvxpy and CVXPYgen
        run: |
          uv venv
          uv pip install .
          git clone --recurse-submodules https://github.com/cvxgrp/cvxpygen.git
          cd cvxpygen
          uv pip install .[dev]
          uv pip install cvxpylayers==0.1.9 "torch>=2.3" jax==0.5.3
      - name: Run CVXPYgen tests
        run: |
          uv run --no-sync pytest cvxpygen/tests
