name: pr_benchmarks

on:
    pull_request:
    push:
        branches:
            - master
        tags:
          - '*'

jobs:
  pr_benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Checkout cvxpy
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install cvxpy dependencies
        run: |
          echo $(git log -5 --oneline)
          pip install .

      - name: Checkout benchmark
        uses: actions/checkout@v2
        with:
          repository: parthb83/benchmarks
          ref: main
          path: benchmark/
        
      - name: Install benchmark dependencies
        run: |
          cd benchmark/
          pip install .
      
      - name: Run benchmarks
        run: |
          cd benchmark/
          asv machine --config asv2.conf.json --yes
          asv continuous --split origin/master HEAD --config asv2.conf.json --quick | tee -a asv_continuous.log
      
      - id: get-comment-body
        run: |
          cd benchmark/
          body="$(cat asv_continuous.log)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo "::set-output name=body::$body"

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'

      - name: Create comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.get-comment-body.outputs.body }}

      - name: Update comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            ${{ steps.get-comment-body.outputs.body }}
          edit-mode: replace
