name: pr_benchmarks

on:
    pull_request:
    push:
        branches:
            - master
        tags:
          - '*'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Checkout cvxpy
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install cvxpy dependencies
        run: |
          echo $(git log -5 --oneline)
          pip install .

      - name: Checkout benchmark
        uses: actions/checkout@v2
        with:
          repository: parthb83/benchmarks
          ref: main
          path: benchmark/
        
      - name: Install benchmark dependencies
        run: |
          cd benchmark/
          pip install .
      
      - name: Run benchmarks on the latest PR commit
        run: |
          cd benchmark/
          asv machine --config asv2.conf.json --yes
          asv continuous --config asv2.conf.json --quick

